name: Publish Dev Container

on:
  push:
    branches: ["main"]
    paths:
      - '.devcontainer/**'
  workflow_dispatch:

jobs:
  pre-build:
    name: Pre-build dev container image
    runs-on: ubuntu-latest
    steps:
      - uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/aloshy-ai/nixcontainer
          cacheFrom: ghcr.io/aloshy-ai/nixcontainer
          push: always
