name: Publish Dev Container

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    name: Build and push container image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Setup Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Install Docker
        uses: docker/setup-buildx-action@v3

      - name: Build and push container
        run: nix run .#pushToGhcr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
