name: Publish Dev Container

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  pre-build:
    name: Pre-build dev container image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        
      - uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/aloshy-ai/nixcontainer
          cacheFrom: ghcr.io/aloshy-ai/nixcontainer
          push: always
